### ISSUE TITLE
CI for ironoxide-android

### ISSUE THREAD

**Issue by clintfred** [IronCoreLabs/ironoxide-java#102]
As an ironoxide-android developer
I want a clear way to build and release the AAR

Probably not for now: Possibly consider packaging shared libs into jars like https://github.com/xerial/sqlite-jdbc

AC
* [x] `release` workflow builds an AAR containing native libs for various Android architectures

**Comment by coltfred** [comment]
The planning moving ahead is that we will not change the java release process. This process is currently as follows:

- `cargo build`
- Use sbt from `java/java/tests` to do `release`.
  - This causes tests to be run and bumps the version in `version.sbt` and tags the repo.
  - Then push the tag

The pushed tag causes the building of all the `.so`s which are used with our java jar.

To this we should add something that causing the building of an AAR using gradle. I think we should do this as a result of pushing the tag. This means that when we actually get to do #96 we can cause the local developer to just create a push a tag and move the `sbt` step from above to be on the CI boxes as well.

@clintfred Would you post which android architectures you're thinking we should build for?

**Comment by cjyar** [comment]
This workflow produced a test release at https://github.com/IronCoreLabs/ironoxide-java/releases/tag/v0.13.1-test2.

**Comment by cjyar** [comment]
The test release exists on sonatype snapshots. Trying to find a URL to it. Trying to determine if the non-snapshot release will get handled properly.
