### ISSUE TITLE
Catch ironoxide JNI loading issues as soon as possible

### ISSUE THREAD

**Issue by clintfred** [IronCoreLabs/ironoxide-java#20]
As devops, building/deploying services integrated with ironoxide-java
I want to know if the service has properly linked ironoxide-java as early as possible

Some ideas were:
* can we detect this at build time of an app using ironoxide-java via some "after compile" sbt step?
* can we make it easier to get ironoxide loaded? See #7 
* if this needs to happen at runtime, perhaps we could show an example of incorporating some sort of simple usage of ironoxide-java into a health endpoint

**Comment by coltfred** [comment]
Alden added a health endpoint to zero-ic-labs to do a simple call across the boundary. 

https://github.com/norwegian-cruise-line/zero-ic-labs/pull/6
