### ISSUE TITLE
[SPIKE] Does ironoxide-java work on a RedHat UBI docker image?

### ISSUE THREAD

**Issue by clintfred** [IronCoreLabs/ironoxide-java#21]
As an application developer using ironoxide-java
I want to run my application on a Redhat Atomic based docker image

Points of concern:
* libc compatibility - we don't statically link in libc, but maybe we could. Maybe we should?
* openssl compatibility - specifically around the loading of root certs. Is the webservice's Let's Encrypt cert supported?

Related: Can we use a pure Rust TLS impl?

**Comment by clintfred** [comment]
@BobWall23 Fidel offered to give us a docker file that he is currently using for atomic... might be worth chasing that down.

From doing a little background reading, it looks like it's possible to use the `musl` target to statically link in libc and `OPENSSL_STATIC` env variable can be used to statically link openssl. If we do statically link either of these, we'll have to be on top of security updates and upgrading the versions on the system/container won't help us. 

I would prefer to stick with dynamic linking of libc, at least and see if we can use a pure rust tls impl, long-term.

**Comment by BobWall23** [comment]
NCLH is switching from Atomic to UBI (Universal Base Image).

**Comment by BobWall23** [comment]
Redirected out effort, given RedHat's change from Atomic to their Universal Base Images (UBI). Need to verify that ironoxide-java works in a UBI8-based container.

**Comment by BobWall23** [comment]
Verified that the ironoxide-java integration tests execute successfully inside a UBI7-based and a UBI8-based container.

**Comment by aldenml** [comment]
This is good news! btw, TIL that there are `ubi` and `ubi-minial`
