### ISSUE TITLE
Configurable API server

### ISSUE THREAD

**Issue by cjyar** [IronCoreLabs/ironoxide-java#46]
- As an IronCore developer, I want to run the same code against dev/stage/prod without recompiling.
- As an IronCore customer, I want to run the SDK in an air-gapped network, using the deployment of `ironcore-id` that's on my local network.

Can we configure the endpoint that we talk to via a Java system property or an environment variable?

**Comment by cjyar** [comment]
This ticket probably belongs in a different repo.

**Comment by ernieturner** [comment]
This can be pretty much already be done with the `IRONCORE_ENV` environment variable. It seems to be sufficiently useful for us now.
