### ISSUE TITLE
Support signed releases

### ISSUE THREAD

**Issue by clintfred** [IronCoreLabs/ironoxide-java#78]
As an ironoxide-java user
I want the released binaries for ironoxide-java to be signed 
so that I can know they haven't been corrupted or tampered with

AC:
* [ ] the latest release is signed and instructions for signing new releases are added to a `RELEASING.md` file
* [x] instructions are provided for verifying the signature

**Comment by coltfred** [comment]
https://gist.github.com/cyphar/21a1b213901a0a0ec19764ac03646ebe is one thing I read on this topic.

**Comment by cjyar** [comment]
Plan:
- [ ] Make a new root identity key which is Ed25519.
- [ ] Associate it with ops@ironcorelabs.com.
- [ ] Sign the new key with the old one, and publish the signature.
- [ ] Generate an Ed25519 signing key for each repo that needs to sign releases. (Initially that’s just ironoxide-java.)
- [ ] Set all the keys to have a 1 year lifetime. (Lifetimes can be increased later.)
- [ ] Set a calendar reminder (or prometheus alert) to renew they keys when they only have 1 month left.
- [ ] Keep the private keys in .iron files.
- [ ] Stop using the old key.

**Comment by cjyar** [comment]
Regarding the original acceptance criteria: I didn't create a RELEASING.md file because it's automated. Just make a tag.

Regarding my newer acceptance criteria:
- I'll look at alerting or reminding as a separate task.
- We can stop using the old key once we automate releasing to Sonatype.
