### ISSUE TITLE
Publish binaries of `ironoxide-java` on release tag

### ISSUE THREAD

**Issue by clintfred** [IronCoreLabs/ironoxide-java#9]
As a dev using `ironoxide-java`
I want a binary available for my OS
so that I don't have to install a rust toolchain to use `ironoxide-java` in my application

AC
* [ ] build for Linux x86-64 and MasOSX
* [ ] releases stored on github releases
* [ ] builds created by Travis on creation of a release tag
* [ ] pushes Java JAR to Maven via sbt. Requires GPG key password as a secret in TravisCI

----
Possibly helpful:
https://rust-lang-nursery.github.io/cli-wg/tutorial/packaging.html

**Comment by skeet70** [comment]
https://github.com/olafurpg/sbt-ci-release
https://alexn.org/blog/2017/08/16/automatic-releases-sbt-travis.html

May be useful for setting up travis releases to Sonatype.
