### ISSUE TITLE
Produce a universal ironoxide binary that works on Mac and aarch64-apple-ios

### ISSUE THREAD

**Issue by zmre** [IronCoreLabs/ironoxide-java#90]
It looks like IronOxide itself can produce a library that works on iOS, according to [this travis log](https://travis-ci.org/IronCoreLabs/ironoxide/jobs/659333754).  However, we need to be able to do this from the wrapper level. That is, we should be able to create a static library (`crate-type = ["staticlib"]`) from the C wrapper.  That wrapper has some extra dependencies in it.

My attempts to do this so far attempted to use [cargo lipo](https://github.com/TimNN/cargo-lipo) to build the universal library, but that is hitting errors.

**Comment by zmre** [comment]
I think you want to build for aarch64-apple-ios and x86_64-apple-ios for the universal bit.

**Comment by clintfred** [comment]
https://medium.com/visly/rust-on-ios-39f799b3c1dd

cross does support those architectures, but I don't think it can produce the universal binary part anyway. I guess we need to look at the actual error and see if we can move past it.

**Comment by ernieturner** [comment]
Closing this issue for now since we can manually build the C/CPP bindings for Apple targets. Building this requires us to use a static lib when using the target for Apple.
