### ISSUE TITLE
release improvements

### ISSUE THREAD

**Issue by cjyar** [IronCoreLabs/ironoxide-java#96]
As an ironoxide-java maintainer, I want a consistent and easy release process.

AC:
- A `RELEASING.md` is in this repository that explains how to make a release. (How to pick version number, coordinate versions between Cargo and sbt, etc.)
- Automate uploading Java artifact to Maven Central.

**Comment by cjyar** [comment]
@coltfred says we should be able to borrow from
https://github.com/IronCoreLabs/cats-scalatest/blob/master/.travis.yml#L35
https://github.com/olafurpg/sbt-ci-release

**Comment by cjyar** [comment]
@coltfred Should I wait on this until you're done with the reorg? Would you like me to do this work on your reorg branch?

**Comment by coltfred** [comment]
I'd wait until we decide exactly how android is going to be built as it might complicate matters depending how we want to publish jars and do the building of all the native artifacts.
