### ISSUE TITLE
Setup Swift to call `init`, `encrypt`, and `decrypt`

### ISSUE THREAD

**Issue by zmre** [IronCoreLabs/ironoxide-java#99]
An initial Swift library should be a wrapper that calls through to Rust via the C bindings.  Initial goal should be to just setup a swift project and get a basic init/encrypt/decrypt roundtrip to work.  Here are some links that will be useful in the process of wrapping C:

* Apple Docs
    * [Swift native data types for interop with C APIs](https://developer.apple.com/documentation/swift/swift_standard_library/c_interoperability)
    * [Using C Structs in Swift](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/using_imported_c_structs_and_unions_in_swift)
    * [Using C Functions in Swift](https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/using_imported_c_functions_in_swift)
    * [https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis](Imported C APIs)
    * [Annotating C code for use in Swift](https://developer.apple.com/documentation/swift/objective-c_and_c_code_customization/customizing_your_c_code_for_swift)

Most of these are easy to find, but I kept losing track of that first bullet item, so hopefully this makes life a bit easier.

**Comment by zmre** [comment]
Murph posted this: https://swiftdoc.org/v3.1/type/unsafemutablerawpointer/#func-load-frombyteoffset_as_

**Comment by ernieturner** [comment]
Initial repo is setup at https://github.com/IronCoreLabs/ironoxide-swift. I don't really know how easy it will be to clone and add that project as I'm not entirely sure which files I should or shouldn't have put into the repo. 

If anybody wants to try it out, let me know and I can walk you through the steps in XCode necessary to hook it all up.
